name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - add-github-action-build-and-lint

jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup GStreamer
        id:   setup_gstreamer
        uses: blinemedical/setup-gstreamer@45324555100927b587d390d8cf3940f91fd3bdc9
        with:
          version: 1.22.0
      - name: checkout
        uses: actions/checkout@v3
      - name: build an example
        run: cd examples/appsink && go run -x .


